# Generated by Django 2.0.3 on 2019-09-06 19:13

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant_item_sub_category', '0001_initial'),
        ('merchant_item_category', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('price_vat_included', models.FloatField(default=0)),
                ('price_vat_excluded', models.FloatField(default=0)),
                ('vat_rate', models.FloatField(default=0.2)),
                ('vat_amount', models.FloatField(default=0)),
                ('article_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(choices=[('act', 'Active'), ('tbr', 'To be reviewed by admin'), ('unv', 'Unavailable'), ('dlt', 'Deleted')], default='tbr', max_length=3)),
                ('display_order', models.IntegerField(default=1)),
                ('has_happy_hour', models.BooleanField(default=False)),
                ('happy_hour_start_hour', models.TimeField(blank=True, null=True)),
                ('happy_hour_end_hour', models.TimeField(blank=True, null=True)),
                ('url_tag', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant_item_category.MerchantItemCategory')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant.Merchant')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant_item_sub_category.MerchantItemSubCategory')),
            ],
        ),
    ]
