# Generated by Django 2.2.5 on 2019-09-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchant_items', to='merchant_item_category.MerchantItemCategory'),
        ),
        migrations.AlterField(
            model_name='merchantitem',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchant_items', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='merchantitem',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchant_items', to='merchant_item_sub_category.MerchantItemSubCategory'),
        ),
    ]
