# Generated by Django 2.2.5 on 2019-09-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_item', '0003_auto_20190914_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantitem',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('tr', 'To be reviewed by admin'), ('uv', 'Unavailable'), ('dt', 'Deleted')], default='tr', max_length=2),
        ),
    ]
