# Generated by Django 2.2.5 on 2020-04-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_item', '0004_auto_20190914_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantitem',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
