# Generated by Django 2.2.5 on 2020-04-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_item', '0007_auto_20200426_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantitem',
            name='is_option',
        ),
        migrations.RemoveField(
            model_name='merchantitem',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='merchantitem',
            name='is_displayed_first_level',
            field=models.BooleanField(default=True),
        ),
    ]
