# Generated by Django 2.0.3 on 2019-09-06 19:13

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('presentation_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('open', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(max_length=14)),
                ('vat_number', models.CharField(blank=True, max_length=500, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=500, null=True)),
                ('address_street', models.CharField(max_length=500)),
                ('address_city', models.CharField(max_length=500)),
                ('address_zip', models.CharField(max_length=500)),
                ('table_quantity', models.IntegerField(default=1)),
                ('url_tag', models.CharField(max_length=50, unique=True)),
                ('service_mode', models.CharField(choices=[('ts', 'Service at the table'), ('bs', 'Service at the bar')], default='ts', max_length=2)),
                ('shop_description', models.TextField(default='Toujours là pour vous servir dans les meilleures conditions. ENJOY!', max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
