# Generated by Django 2.2.5 on 2019-09-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='owner_name',
            field=models.CharField(default='JC', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchant',
            name='url_tag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='vat_number',
            field=models.CharField(default='1233333', max_length=500),
            preserve_default=False,
        ),
    ]
