# Generated by Django 2.2.5 on 2020-04-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20190908_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='accept_cash',
            field=models.BooleanField(default=False),
        ),
    ]
