# Generated by Django 2.2.5 on 2020-04-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_merchant_accept_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='service_mode',
        ),
        migrations.AddField(
            model_name='merchant',
            name='accept_service_bar',
            field=models.BooleanField(default=False),
        ),
    ]
