# Generated by Django 2.2.5 on 2020-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20200422_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='accept_service_table',
            field=models.BooleanField(default=False),
        ),
    ]
