# Generated by Django 2.2.5 on 2019-09-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantbankaccount',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant.Merchant'),
        ),
    ]
