# Generated by Django 2.2.5 on 2019-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_loyalty_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantloyaltyprogram',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
