# Generated by Django 2.0.3 on 2019-09-06 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('merchant_loyalty_program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyaltyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point_count', models.FloatField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer')),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant_loyalty_program.MerchantLoyaltyProgram')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLoyaltyCardDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point_modification', models.FloatField(default=0)),
                ('point_modification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer')),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant_loyalty_program.MerchantLoyaltyProgram')),
            ],
        ),
    ]
