# Generated by Django 2.2.5 on 2019-09-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_loyalty_card', '0002_auto_20190910_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerloyaltycardhistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerloyaltycardhistory',
            name='loyalty_program',
        ),
        migrations.AddField(
            model_name='customerloyaltycardhistory',
            name='customer_loyalty_card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_loyalty_card_histories', to='customer_loyalty_card.CustomerLoyaltyCard'),
            preserve_default=False,
        ),
    ]
