# Generated by Django 2.0.3 on 2019-09-06 19:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_card_id', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cvc_check', models.CharField(blank=True, max_length=100, null=True)),
                ('dynamic_last4', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_month', models.IntegerField(default=1)),
                ('exp_year', models.IntegerField(default=2019)),
                ('fingerprint', models.CharField(blank=True, max_length=100, null=True)),
                ('funding', models.CharField(blank=True, max_length=100, null=True)),
                ('last4', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tokenization_method', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer')),
            ],
        ),
    ]
