# Generated by Django 2.2.5 on 2019-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_credit_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercard',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('de', 'Deleted')], default='ac', max_length=2),
        ),
    ]
