# Generated by Django 2.2.5 on 2019-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_credit_card', '0002_customercard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercard',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('ic', 'Inactive'), ('de', 'Deleted')], default='ac', max_length=2),
        ),
    ]
