# Generated by Django 2.2.5 on 2019-09-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_charge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercharge',
            name='captured',
        ),
        migrations.AddField(
            model_name='customercharge',
            name='status',
            field=models.CharField(choices=[('dr', 'Draft'), ('st', 'Sent'), ('do', 'Done'), ('er', 'Error')], default='dr', max_length=2),
        ),
    ]
