# Generated by Django 2.2.5 on 2020-04-19 22:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='invoice_file',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='invoice_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
