# Generated by Django 2.2.5 on 2019-09-07 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_billing_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantbillingplan',
            name='starting_date',
            field=models.DateTimeField(default=datetime.date(2019, 9, 7)),
        ),
    ]
