# Generated by Django 2.2.5 on 2019-09-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_billing_plan', '0002_auto_20190907_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantbillingplan',
            name='starting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
