# Generated by Django 2.2.5 on 2019-09-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_billing_plan', '0004_auto_20190907_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantbillingplan',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merchantbillingplan',
            name='starting_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
