# Generated by Django 2.2.5 on 2020-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
