# Generated by Django 2.2.5 on 2020-04-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0002_customerorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order_refunded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='order_refused_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
