# Generated by Django 2.2.5 on 2020-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0003_auto_20200419_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='st_checkout_session_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='st_customer_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_state',
            field=models.CharField(choices=[('dr', 'Draft'), ('pa', 'Paid'), ('pr', 'In Preparation'), ('do', 'Done'), ('er', 'Payment Error'), ('re', 'Refused'), ('rf', 'Refunded'), ('de', 'Deleted'), ('cp', 'Completed')], default='dr', max_length=2),
        ),
    ]
