# Generated by Django 2.2.5 on 2020-04-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0004_auto_20200424_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer'),
        ),
    ]
