# Generated by Django 2.0.3 on 2019-09-06 19:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_order', '0001_initial'),
        ('merchant_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=1)),
                ('ready', models.BooleanField(default=False)),
                ('unit_amount_vat_included', models.FloatField(default=0)),
                ('unit_amount_vat_excluded', models.FloatField(default=0)),
                ('unit_vat_amount', models.FloatField(default=0)),
                ('vat_rate', models.FloatField(default=0.2)),
                ('total_amount_vat_included', models.FloatField(default=0)),
                ('total_amount_vat_excluded', models.FloatField(default=0)),
                ('total_vat_amount', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant_item.MerchantItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_order.CustomerOrder')),
            ],
        ),
    ]
