# Generated by Django 2.2.5 on 2019-09-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_item_customization_option', '0002_auto_20190908_1640'),
        ('merchant_item_customization', '0002_auto_20190908_1640'),
        ('customer_order_line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderline',
            name='item_customization',
            field=models.ManyToManyField(to='merchant_item_customization.MerchantItemCustomization'),
        ),
        migrations.AddField(
            model_name='customerorderline',
            name='item_customization_option',
            field=models.ManyToManyField(to='merchant_item_customization_option.MerchantItemCustomizationOption'),
        ),
    ]
