# Generated by Django 2.2.5 on 2019-09-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_line', '0002_auto_20190911_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_order_lines', to='merchant_item.MerchantItem'),
        ),
        migrations.AlterField(
            model_name='customerorderline',
            name='item_customization',
            field=models.ManyToManyField(related_name='customer_order_lines', to='merchant_item_customization.MerchantItemCustomization'),
        ),
        migrations.AlterField(
            model_name='customerorderline',
            name='item_customization_option',
            field=models.ManyToManyField(related_name='customer_order_lines', to='merchant_item_customization_option.MerchantItemCustomizationOption'),
        ),
        migrations.AlterField(
            model_name='customerorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_order_lines', to='customer_order.CustomerOrder'),
        ),
    ]
