# Generated by Django 2.2.5 on 2020-04-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_line', '0003_auto_20190911_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderline',
            name='item_customization',
            field=models.ManyToManyField(blank=True, related_name='customer_order_lines', to='merchant_item_customization.MerchantItemCustomization'),
        ),
        migrations.AlterField(
            model_name='customerorderline',
            name='item_customization_option',
            field=models.ManyToManyField(blank=True, related_name='customer_order_lines', to='merchant_item_customization_option.MerchantItemCustomizationOption'),
        ),
    ]
