# Generated by Django 2.2.5 on 2020-04-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_line', '0005_auto_20200427_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderline',
            name='parent_order_line_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
