# Generated by Django 2.0.3 on 2019-09-06 19:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant_item_customization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantItemCustomizationOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('default_quantity', models.IntegerField(default=0)),
                ('max_permitted', models.IntegerField(default=1)),
                ('min_permitted', models.IntegerField(default=1)),
                ('price_vat_included', models.FloatField(default=0)),
                ('price_vat_excluded', models.FloatField(default=0)),
                ('vat_rate', models.FloatField(default=0.2)),
                ('vat_amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('act', 'Active'), ('tbr', 'To be reviewed by admin'), ('unv', 'Unavailable'), ('dlt', 'Deleted')], default='tbr', max_length=3)),
                ('display_order', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant_item_customization.MerchantItemCustomization')),
            ],
        ),
    ]
