# Generated by Django 2.2.5 on 2019-09-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_item_customization_option', '0002_auto_20190908_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantitemcustomizationoption',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('tr', 'To be reviewed by admin'), ('uv', 'Unavailable'), ('dt', 'Deleted')], default='tr', max_length=2),
        ),
    ]
