# Generated by Django 2.2.5 on 2020-04-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_item', '0004_auto_20190914_1940'),
        ('merchant_item_customization_option', '0003_auto_20190914_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantitemcustomizationoption',
            name='price_vat_excluded',
        ),
        migrations.RemoveField(
            model_name='merchantitemcustomizationoption',
            name='price_vat_included',
        ),
        migrations.RemoveField(
            model_name='merchantitemcustomizationoption',
            name='status',
        ),
        migrations.RemoveField(
            model_name='merchantitemcustomizationoption',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='merchantitemcustomizationoption',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='merchantitemcustomizationoption',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='merchant_item.MerchantItem'),
        ),
    ]
