# Generated by Django 2.2.5 on 2020-04-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_item_customization_option', '0004_auto_20200426_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantitemcustomizationoption',
            name='name',
        ),
    ]
