# Generated by Django 2.2.5 on 2019-09-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_charge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantcharge',
            name='merchant',
        ),
    ]
