# Generated by Django 2.2.5 on 2019-09-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_charge', '0004_auto_20190914_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantcharge',
            name='status',
        ),
    ]
